### ISSUE TITLE
api-ms-win-core-path-l1-1-1.ddl is missing

### ISSUE THREAD

**Issue by av1444** [YarostheLaunchpadder/MissionPlanner-to-Litchi#2]
Hi. Thanks for this coverter. I have an issue: When trying to start the script, a pop-up windows appears saying: The program can't start because api-ms-win-core-path-l1-1-1.ddl is missing from your computer. 
I searched and found the .dll file on the computer so I don't know what the problem is. I also checked it on another computer and the message was the same. Any thoughts?

**Comment by YarostheLaunchpadder** [comment]
@av1444 If you have Avast, you should disable it temporarely because it messes with the exe sometimes, as it is not signed.
Also, which version of Windows do you have?
If you could also provide some info about your PC (CPU, RAM, GPU) it would be very helpful.
Also make sure you're running the exe from the desktop and not in a protected folder.

**Comment by av1444** [comment]
@YarostheLaunchpadder It seems that the Windows version is the problem. I have Windows 7 installed on my computer. I did check and it runs on Windows 8 and 10.

**Comment by YarostheLaunchpadder** [comment]
@av1444 Yes, that might be the problem. According to Microsoft, Windows 7 is considered obsolete, and most new versions of programs will not run.
I compiled this script on Windows 11, so I doubt it will work correctly on Windows 7. 
But there is a fix, if you install Python on your Windows 7 PC, then you can make a file on your desktop that ends with the `.py `extension, then you copy and paste the code from the `main.py` from this repository, paste and save it into your file. Then just run the file by double-clicking. That's a possible fix, however I don't know if new versions of Python work on Win 7, if they don't, then try installing Python 3.7 or earlier.

**Comment by av1444** [comment]
@YarostheLaunchpadder  Thank you for that workaround, it runs perfectly now!
