### ISSUE TITLE
App closes after submitting .waypoints path

### ISSUE THREAD

**Issue by j-abellera** [YarostheLaunchpadder/MissionPlanner-to-Litchi#26]
The windows app is crashing? I open the exe and a terminal asks for the waypoints path. As soon as I submit the path, the terminal closes. I don't see a converted file anywhere. I am not sure what I am doing wrong.

**Comment by YarostheLaunchpadder** [comment]
Yep, it is crashing. Go to the folder you have the exe, right click, open terminal there. Then type the name of the exe in the terminal. It will run the app inside the terminal, and you will see the error. Submit it here.

**Comment by JoeKae** [comment]
I think the .exe is outdated anyway. The release should be updated.

**Comment by YarostheLaunchpadder** [comment]
@JoeKae Could you compile the new version to EXE and upload it, please?

**Comment by JoeKae** [comment]
On the weekend i will have a look.

**Comment by JoeKae** [comment]
#28

**Comment by JoeKae** [comment]
@j-abellera Try release version 1.1.0 and give feedback.

**Comment by JoeKae** [comment]
Since I haven't received any feedback, I assume that the issue has been resolved and everything is functioning properly now.
