### ISSUE TITLE
Unable to convert

### ISSUE THREAD

**Issue by rohitmalhotra2203** [YarostheLaunchpadder/MissionPlanner-to-Litchi#3]
I have followed your steps to creat a mission in mission planner then convert the .mission file to .csv using the tool how ever the script is closing prematurely without generating a result . could you please help .
thanks 
Rohit

**Comment by YarostheLaunchpadder** [comment]
Could you please run the script from cmd to get the error?

**Comment by rohitmalhotra2203** [comment]
![Untitled](https://user-images.githubusercontent.com/16113355/165496301-6635750e-2421-495c-9f8c-845dfb99b804.jpg)

**Comment by YarostheLaunchpadder** [comment]
The .waypoints file should be on Desktop, the same place as the script.

**Comment by rohitmalhotra2203** [comment]
i tried and failed ..not working for me

**Comment by rohitmalhotra2203** [comment]
error in the .py file perhaps 
![Untitled](https://user-images.githubusercontent.com/16113355/165663973-b360ec45-c6b2-4b06-87eb-d03f763c081e.jpg)

**Comment by YarostheLaunchpadder** [comment]
Okay, I will try to fix it today.

**Comment by rohitmalhotra2203** [comment]
yes, I have python on my PC. 
Would be real nice if you could send me the edited code.

**Comment by rohitmalhotra2203** [comment]
also giving an invalid syntax in line 6 when you run the python file

**Comment by YarostheLaunchpadder** [comment]
@rohitmalhotra2203 Here is the code, it will save the converted file in the same location as your .py file with the following code: https://pastebin.com/Vfb4zMZD

Please run it from a folder that is not synced with OneDrive if possible.

**Comment by VladimirPobedinskiy** [comment]
> also giving an invalid syntax in line 6 when you run the python file

Try my fork. In Releases you can find archive with exe, just open mission with it. result csv placed near.
https://github.com/VladimirPobedinskiy/MissionPlanner-to-Litchi/releases/tag/release

**Comment by rohitmalhotra2203** [comment]
> > also giving an invalid syntax in line 6 when you run the python file
> 
> Try my fork. In Releases you can find archive with exe, just open mission with it. result csv placed near. https://github.com/VladimirPobedinskiy/MissionPlanner-to-Litchi/releases/tag/release

Works like a charm
Thank you so much YarostheLaunchpadder and VladimirPobedinskiy 
You guys are the best
