### ISSUE TITLE
Gimbal control (DO_MOUNT_CONTROL) Ignored

### ISSUE THREAD

**Issue by WarrenSchultz** [YarostheLaunchpadder/MissionPlanner-to-Litchi#4]
I inserted a mount control waypoint in the MP interface to set the gimbal to -90deg, but that is dropped in the conversion process. (As are the takeoff and RTL commands)

![image](https://user-images.githubusercontent.com/8450968/173206676-2d85cc8d-6c44-41d6-9a22-c0f50f0f84bd.png)

**Comment by JoeKae** [comment]
issue #13
