### ISSUE TITLE
"Stay for" and "Take photo" actions

### ISSUE THREAD

**Issue by brunoaduarte** [YarostheLaunchpadder/MissionPlanner-to-Litchi#7]
Hi, I've noticed that "Mission Planner" and your "MissionPlanner-to-Litchi" converter doesn't include the actions for the drone to take photos in pre-determined spots. How this "auto-photo" mode you mentioned in the README works? How do Litchi knows the correct place to take the photos? I've set the path to Straight Lines.

Also the "Above Ground" fields should be checked by default in the CSV creation (conversion) process so Litchi can calculate the correct height for each location when importing the mission.

**Comment by JoeKae** [comment]
> How do Litchi knows the correct place to take the photos?

Take a close look at the waypoints in Litchi. There you will find intervals in which the images are captured. These come from the Mission Planner survey tool.

**Comment by JoeKae** [comment]
> Also the "Above Ground" fields should be checked by default in the CSV creation (conversion) process so Litchi can calculate the correct height for each location when importing the mission.

Issue #8 

> Hi, I've noticed that "Mission Planner" and your "MissionPlanner-to-Litchi" converter doesn't include the actions for the drone to take photos in pre-determined spots. How this "auto-photo" mode you mentioned in the README works? How do Litchi knows the correct place to take the photos? I've set the path to Straight Lines.

Add explanation how it works to documentation.

**Comment by JoeKae** [comment]
Issue #13
