### ISSUE TITLE
AGL not set

### ISSUE THREAD

**Issue by JoeKae** [YarostheLaunchpadder/MissionPlanner-to-Litchi#8]
If set to terrain relative height in mission planner, the kml output from mission planner is using agl heights. But the converted waypoints by this script are not set to agl.

* Check if whis can be set in a waypoint file
* add this feature

**Comment by YarostheLaunchpadder** [comment]
I will check on this soon! Thanks for the report.

**Comment by JoeKae** [comment]
If I find the time, I will dive into it and create a PR.
